---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= 클라우드 데이터 센스에 관한 FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 클라우드 데이터 감지 서비스

다음 질문을 통해 클라우드 데이터 센스에 대한 일반적인 이해를 얻을 수 있습니다.



=== 클라우드 데이터 센스의 정의

Cloud Data Sense는 인공 지능(AI) 기반 기술을 사용하여 데이터 컨텍스트를 이해하고 스토리지 시스템 전체에서 중요한 데이터를 식별하는 데 도움이 되는 클라우드 오퍼링입니다. 시스템은 Cloud Manager Canvas에 추가한 작업 환경과 Data Sense가 네트워크를 통해 액세스할 수 있는 다양한 유형의 데이터 소스일 수 있습니다. <<What sources of data can be scanned with Data Sense,아래 전체 목록을 참조하십시오>>.

Cloud Data Sense는 GDPR, CCPA, HIPAA 등과 같은 데이터 개인 정보 보호 및 민감도에 대한 새로운 데이터 규정 준수 규정을 해결하기 위해 미리 정의된 매개 변수(예: 중요한 정보 유형 및 범주)를 제공합니다.



=== Cloud Data Sense를 사용해야 하는 이유는 무엇입니까?

클라우드 데이터 센스를 통해 다음과 같은 이점을 얻을 수 있습니다.

* 데이터 규정 준수 및 개인정보 보호 규정 준수
* 기존 시스템에서 클라우드로 데이터 마이그레이션
* 데이터 보존 정책 준수
* GDPR, CCPA, HIPAA 및 기타 데이터 개인 정보 보호 규정에 따라 데이터 주체에 대응하여 특정 데이터를 쉽게 찾고 보고할 수 있습니다.




=== Cloud Data Sense의 일반적인 사용 사례는 무엇입니까?

* 개인 식별 정보(PII)를 식별합니다.
* GDPR 및 CCPA 개인 정보 보호 규정에서 요구하는 광범위한 중요 정보를 식별합니다.
* 새로운 데이터 개인 정보 보호 규정 및 예정된 데이터 개인 정보 보호 규정을 준수합니다.


https://cloud.netapp.com/cloud-compliance["클라우드 데이터 센스의 사용 사례에 대해 자세히 알아보십시오"^].



=== Cloud Data Sense는 어떻게 작동합니까?

Cloud Data Sense는 Cloud Manager 시스템 및 스토리지 시스템과 함께 또 다른 인공 지능 계층을 구축합니다. 그런 다음 볼륨, 버킷, 데이터베이스 및 기타 스토리지 계정의 데이터를 검색하고 검색된 데이터 인사이트를 인덱싱합니다. 데이터 센스는 정규식과 패턴 일치를 기반으로 일반적으로 구축되는 대체 솔루션과 달리 인공 지능과 자연어 처리를 모두 활용합니다. Cloud Data Sense는 AI를 사용하여 정확한 탐지 및 분류를 위해 데이터에 대한 상황별 이해를 제공합니다. AI는 최신 데이터 유형과 규모에 맞게 설계되었으므로 AI를 중심으로 구동됩니다. 또한 데이터 컨텍스트를 이해하여 강력하고 정확한 검색 및 분류를 제공합니다.

link:concept-cloud-compliance.html["클라우드 데이터 센스의 작동 방식에 대해 자세히 알아보십시오"^].



=== Cloud Data Sense는 내 데이터를 얼마나 자주 스캔합니까?

데이터는 자주 변경되므로 Cloud Data Sense는 데이터에 영향을 주지 않고 데이터를 지속적으로 검색합니다. 초기 데이터 스캔에는 시간이 오래 걸릴 수 있지만 후속 스캔에서는 증분 변경 사항만 스캔하므로 시스템 스캔 시간이 줄어듭니다.

link:concept-cloud-compliance.html#how-scans-work["스캔 작동 방식에 대해 알아보십시오"].

데이터 스캔은 스토리지 시스템과 데이터에 경미한 영향을 줍니다. 그러나 아주 작은 충격에도 신경 쓰면 데이터 센스를 구성하여 "느린" 스캔을 수행할 수 있습니다. link:task-managing-compliance.html#reducing-the-data-sense-scan-speed["스캔 속도를 줄이는 방법을 참조하십시오"].



=== Cloud Data Sense는 어떤 구축 모델을 지원합니까?

Cloud Data Sense는 일반적으로 클라우드 관리자 인터페이스를 통해 서비스가 제공되는 SaaS 모델을 사용하여 구축됩니다. Cloud Data Sense를 구축하면 온프레미스, 클라우드 및 하이브리드 환경을 비롯한 거의 모든 곳에서 시스템을 검색하고 보고할 수 있습니다. 안전한 설치의 경우 Cloud Manager 및 Cloud Data Sense를 "다크 사이트" 모델에 배포할 수 있습니다. 이 모델은 온프레미스에 패키지로 설치되며 외부 네트워크 연결이 필요하지 않습니다.



=== 내 브라우저와 데이터 감지 간에 전송되는 개인 데이터에 누가 액세스할 수 있습니까?

아니요 브라우저와 Data Sense 인스턴스 간에 전송되는 개인 데이터는 엔드 투 엔드 암호화로 보호되며, 이는 NetApp과 타사에서 데이터를 읽을 수 없음을 의미합니다. 액세스를 요청하고 승인하지 않는 한 데이터 센스에서 NetApp과 데이터 또는 결과를 공유하지 않습니다.



=== 클라우드 데이터 센스에서 보고서를 제공합니까?

예. Cloud Data Sense에서 제공하는 정보는 조직의 다른 이해 관계자와 관련이 있을 수 있으므로 보고서를 생성하여 통찰력을 공유할 수 있습니다. 데이터 센스에 사용할 수 있는 보고서는 다음과 같습니다.

개인 정보 보호 위험 평가 보고서:: 개인 정보 보호 관련 정보와 개인 정보 보호 위험 점수를 제공합니다. link:task-generating-compliance-reports.html#privacy-risk-assessment-report["자세한 정보"^].
데이터 주체 액세스 요청 보고서:: 데이터 주체의 특정 이름 또는 개인 식별자에 관한 정보가 포함된 모든 파일의 보고서를 추출할 수 있습니다. link:task-responding-to-dsar.html["자세한 정보"^].
PCI DSS 보고서:: 파일 전체에서 신용 카드 정보의 배포를 식별하는 데 도움이 됩니다. link:task-generating-compliance-reports.html#pci-dss-report["자세한 정보"^].
HIPAA 보고서:: 파일에 대한 상태 정보 배포를 식별하는 데 도움이 됩니다. link:task-generating-compliance-reports.html#hipaa-report["자세한 정보"^].
데이터 매핑 보고서:: 작업 환경의 파일 크기 및 수에 대한 정보를 제공합니다. 여기에는 사용 용량, 데이터 사용 기간, 데이터 크기 및 파일 유형이 포함됩니다. link:task-generating-compliance-reports.html#data-mapping-report["자세한 정보"^].
특정 정보 유형에 대한 보고서입니다:: 개인 데이터와 민감한 개인 데이터가 포함된 식별된 파일에 대한 세부 정보가 포함된 보고서를 사용할 수 있습니다. 범주 및 파일 유형별로 분류된 파일도 볼 수 있습니다. link:task-controlling-private-data.html["자세한 정보"^].




=== 스캔 성능이 달라집니까?

스캔 성능은 네트워크 대역폭 및 환경의 평균 파일 크기에 따라 달라질 수 있습니다. 또한 호스트 시스템의 크기 특성(클라우드 또는 온프레미스)에 따라 달라질 수 있습니다. 을 참조하십시오 link:concept-cloud-compliance.html#the-cloud-data-sense-instance["클라우드 데이터 감지 인스턴스"] 및 link:task-deploy-cloud-compliance.html["클라우드 데이터 센스를 구축하는 중입니다"] 를 참조하십시오.

처음에 새 데이터 소스를 추가할 때 전체 "분류" 스캔이 아닌 "매핑" 스캔만 수행하도록 선택할 수도 있습니다. 내부 데이터를 보기 위해 파일에 액세스하지 않기 때문에 데이터 소스에서 매핑을 매우 빠르게 수행할 수 있습니다. link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["매핑 스캔과 분류 스캔의 차이를 확인하십시오."]



=== 클라우드 데이터 센스를 활성화하려면 어떻게 해야 합니까?

먼저 Cloud Manager에 Cloud Data Sense의 인스턴스를 배포해야 합니다. 인스턴스가 실행되면 * Data Sense * 탭에서 또는 특정 작업 환경을 선택하여 기존 작업 환경, 데이터베이스 및 기타 데이터 원본에 대한 서비스를 활성화할 수 있습니다.

link:task-getting-started-compliance.html["시작하는 방법을 알아보십시오"^].


NOTE: 데이터 소스에서 클라우드 데이터 센스를 활성화하면 즉시 초기 스캔이 됩니다. 스캔 결과는 잠시 후에 표시됩니다.



=== 클라우드 데이터 센스를 비활성화하려면 어떻게 해야 합니까?

데이터 감지 구성 페이지에서 개별 작업 환경, 데이터베이스, 파일 공유 그룹, OneDrive 계정 또는 SharePoint 계정을 검색할 때 Cloud Data Sense를 사용하지 않도록 설정할 수 있습니다.

link:task-managing-compliance.html["자세한 정보"^].


NOTE: Cloud Data Sense 인스턴스를 완전히 제거하려면 클라우드 공급자의 포털 또는 사내 위치에서 Data Sense 인스턴스를 수동으로 제거해야 합니다.



=== ONTAP 볼륨에서 데이터 계층화가 활성화된 경우 어떻게 됩니까?

콜드 데이터를 오브젝트 스토리지에 계층하는 ONTAP 시스템에서 클라우드 데이터 센스를 활성화할 수도 있습니다. 데이터 계층화가 활성화된 경우 데이터 센스(Data Sense)는 디스크에 있는 데이터와 오브젝트 스토리지에 대한 콜드 데이터 등 모든 데이터를 검색합니다.

규정 준수 검사에서는 콜드 데이터를 가열하지 않으며 오브젝트 스토리지까지 차갑게 유지됩니다.



=== Cloud Data Sense는 내 조직에 알림을 전송할 수 있습니까?

예. 정책 기능과 함께 정책이 결과를 반환할 때 Cloud Manager 사용자(매일, 매주 또는 매월)에게 이메일 경고를 보내 데이터를 보호하기 위한 알림을 받을 수 있습니다. 에 대해 자세히 알아보십시오 link:task-org-private-data.html#controlling-your-data-using-policies["정책"^].

또한 조직에서 내부적으로 공유할 수 있는 관리 페이지 및 조사 페이지에서 상태 보고서를 다운로드할 수도 있습니다.



=== 조직의 요구에 맞게 서비스를 사용자 정의할 수 있습니까?

클라우드 데이터 센스를 통해 즉각적인 데이터 인사이트를 얻을 수 있습니다. 이러한 통찰력을 추출하여 조직의 요구에 활용할 수 있습니다.

또한 * Data Fusion * 기능을 사용하여 스캔 중인 데이터베이스의 특정 열에 있는 기준에 따라 데이터 센스를 통해 모든 데이터를 검색할 수 있습니다. 기본적으로 사용자 지정 개인 데이터 유형을 만들 수 있습니다.

link:task-managing-data-fusion.html#creating-custom-personal-data-identifiers-from-your-databases["자세한 정보"^].



=== Cloud Data Sense는 내 파일에 포함된 AIP 레이블과 함께 사용할 수 있습니까?

예. 구독한 경우 Cloud Data Sense에서 검색 중인 파일에서 AIP 레이블을 관리할 수 있습니다 link:https://azure.microsoft.com/en-us/services/information-protection/["AIP(Azure Information Protection)"^]. 파일에 이미 할당된 레이블을 보고, 파일에 레이블을 추가하고, 기존 레이블을 변경할 수 있습니다.

link:task-org-private-data.html#categorizing-your-data-using-aip-labels["자세한 정보"^].



=== 클라우드 데이터 감지 정보를 특정 사용자로 제한할 수 있습니까?

예, Cloud Data Sense는 Cloud Manager와 완벽하게 통합됩니다. Cloud Manager 사용자는 작업 영역 권한에 따라 볼 수 있는 작업 환경에 대한 정보만 볼 수 있습니다.

또한 특정 사용자가 데이터 감지 설정을 관리할 수 없는 상태에서 데이터 감지 스캔 결과만 볼 수 있도록 하려면 해당 사용자에게 _Cloud Compliance Viewer_역할을 할당할 수 있습니다.

link:concept-cloud-compliance.html#user-access-to-compliance-information["자세한 정보"^].



=== 지원되는 클라우드 공급자는 무엇입니까?

Cloud Data Sense는 Cloud Manager의 일부로 작동하며 AWS, Azure 및 GCP를 지원합니다. 이를 통해 조직은 다양한 클라우드 공급자 전반에서 통합된 개인 정보 보호 가시성을 확보할 수 있습니다.



== 소스 시스템 및 데이터 유형의 유형입니다

다음 질문은 스캔할 수 있는 스토리지 유형 및 스캔할 데이터 유형과 관련되어 있습니다.



=== 데이터 센스를 사용하여 스캔할 수 있는 데이터 소스는 무엇입니까?

Cloud Data Sense는 Cloud Manager Canvas에 추가한 작업 환경과 Data Sense가 네트워크를 통해 액세스할 수 있는 다양한 유형의 데이터 소스에서 데이터를 검색할 수 있습니다.

* 작업 환경: *

* Cloud Volumes ONTAP(AWS, Azure 또는 GCP에 구축)
* 온프레미스 ONTAP 클러스터
* Azure NetApp Files
* ONTAP용 Amazon FSx
* Amazon S3


* 데이터 소스: *

* 비 NetApp 파일 공유
* 오브젝트 스토리지(S3 프로토콜 사용)
* 데이터베이스(Amazon RDS, MongoDB, MySQL, Oracle, PostgreSQL, SAP HANA, SQL Server)
* OneDrive 계정
* SharePoint 계정
* Google Drive 계정


Data Sense는 NFS 버전 3.x, 4.0, 4.1 및 CIFS 버전 1.x, 2.0, 2.1 및 3.0을 지원합니다.



=== 정부 지역에 배포할 때 제한 사항이 있습니까?

Connector가 정부 지역(AWS GovCloud, Azure Gov 또는 Azure DoD)에 배포되면 Cloud Data Sense가 지원됩니다. 이러한 방식으로 구축할 경우 Data Sense는 다음과 같은 제한 사항을 따릅니다.

* OneDrive 계정, SharePoint 계정 및 Google Drive 계정을 검색할 수 없습니다.
* Microsoft Azure 정보 보호(AIP) 레이블 기능은 통합할 수 없습니다.




=== 인터넷 액세스 없이 사이트에 데이터 센스를 설치할 경우 어떤 데이터 소스를 검색할 수 있습니까?

Data Sense는 사내 사이트에 로컬인 데이터 소스에서만 데이터를 스캔할 수 있습니다. 이때 데이터 센스(Data Sense)는 "어두운" 사이트에서 다음과 같은 로컬 데이터 소스를 스캔할 수 있습니다.

* 온프레미스 ONTAP 시스템
* 데이터베이스 스키마
* 비NetApp NFS 또는 CIFS 파일 공유
* S3(Simple Storage Service) 프로토콜을 사용하는 오브젝트 스토리지




=== 지원되는 파일 유형은 무엇입니까?

Cloud Data Sense는 모든 파일에서 범주 및 메타데이터 정보를 검색하고 대시보드의 파일 형식 섹션에 모든 파일 형식을 표시합니다.

데이터 센스에서 PII(개인 식별 정보)를 감지하거나 DSAR 검색을 수행할 때 다음 파일 형식만 지원됩니다.

'+.csv, .dcm, .dicom, .DOC, .DOCX, .JSON, .pdf, .PPTX, .rtf, .TXT, XLS, .XLSX, Docs, Sheets, Slides+'



=== Cloud Data Sense는 어떤 종류의 데이터 및 메타데이터를 캡처합니까?

Cloud Data Sense를 사용하면 데이터 소스에서 일반적인 "매핑" 스캔 또는 전체 "분류" 스캔을 실행할 수 있습니다. 매핑은 데이터에 대한 상위 수준의 개요만 제공하는 반면 분류는 데이터에 대한 세부 수준의 스캐닝을 제공합니다. 내부 데이터를 보기 위해 파일에 액세스하지 않기 때문에 데이터 소스에서 매핑을 매우 빠르게 수행할 수 있습니다.

* 데이터 매핑 스캔.
+
Data Sense는 메타데이터만 검색합니다. 이 기능은 전체 데이터 관리 및 거버넌스, 빠른 프로젝트 범위 지정, 대규모 부동산 및 우선순위 지정에 유용합니다. 데이터 매핑은 메타데이터를 기반으로 하며 * 빠른 * 스캔으로 간주됩니다.

+
고속 스캔 후 데이터 매핑 보고서를 생성할 수 있습니다. 이 보고서는 리소스 활용도, 마이그레이션, 백업, 보안 및 규정 준수 프로세스에 대한 의사 결정을 돕기 위해 기업 데이터 소스에 저장된 데이터에 대한 개요입니다.

* 데이터 분류(딥) 스캔.
+
데이터 센스(Data Sense)는 고객 환경 전체에서 표준 프로토콜과 읽기 전용 권한을 사용하여 스캔합니다. Select 파일은 랜섬웨어 관련 중요 비즈니스 관련 데이터, 개인 정보 및 문제를 대상으로 열렸다 스캔됩니다.

+
전체 스캔 후에는 데이터 조사 페이지의 데이터 보기 및 구체화, 파일 내 이름 검색, 원본 파일 복사, 이동 및 삭제 등과 같이 데이터에 적용할 수 있는 여러 가지 추가 데이터 감지 기능이 있습니다.





== 추가 수익 실적을

다음 질문은 Cloud Data Sense를 사용하기 위한 라이센싱 및 비용과 관련된 것입니다.



=== Cloud Data Sense 비용은 얼마입니까?

클라우드 데이터 센스를 사용하는 비용은 스캔하는 데이터의 양에 따라 다릅니다. Cloud Manager 작업 공간에서 Data Sense가 스캔하는 첫 번째 1TB의 데이터는 무료입니다. 이 제한에 도달한 후 1TB를 초과하는 데이터를 계속 스캔하려면 다음 중 하나가 필요합니다.

* 클라우드 공급자 또는 에서 Cloud Manager Marketplace 목록에 대한 구독
* BYOL(Bring-Your-Own-License) 방식으로 NetApp의 BYOL(Bring-Your-License


을 참조하십시오 https://cloud.netapp.com/netapp-cloud-data-sense#Pricing["가격"^] 를 참조하십시오.



=== BYOL 용량 제한에 도달하면 어떻게 됩니까?

BYOL 용량 제한에 도달하면 Data Sense는 계속 실행되지만, 스캔된 데이터에 대한 정보를 볼 수 없도록 대시보드에 대한 액세스가 차단됩니다. 라이센스 한도 내에서 용량 사용을 잠재적으로 가져오기 위해 스캔되는 볼륨 수를 줄이려는 경우 구성 페이지만 사용할 수 있습니다. BYOL 라이센스를 갱신하여 데이터 센스에 대한 전체 액세스를 회복해야 합니다.



== 커넥터 전개

다음 질문은 Cloud Manager Connector와 관련이 있습니다.



=== 커넥터란 무엇입니까?

Connector는 클라우드 계정 내부 또는 사내에서 컴퓨팅 인스턴스에서 실행되는 소프트웨어로, Cloud Manager에서 클라우드 리소스를 안전하게 관리할 수 있도록 지원합니다. 클라우드 데이터 센스를 사용하려면 커넥터를 구축해야 합니다.



=== 커넥터를 어디에 설치해야 합니까?

* AWS의 Cloud Volumes ONTAP, ONTAP용 Amazon FSx 또는 AWS S3 버킷에서 데이터를 스캔할 때는 AWS의 커넥터를 사용합니다.
* Azure 또는 Azure NetApp Files의 Cloud Volumes ONTAP에서 데이터를 스캔할 때 Azure의 커넥터를 사용합니다.
* GCP의 Cloud Volumes ONTAP에서 데이터를 스캔할 때 GCP의 커넥터를 사용합니다.
* 사내 ONTAP 시스템, 타사 파일 공유, 범용 S3 오브젝트 스토리지, 데이터베이스, OneDrive 폴더, SharePoint 계정, Google Drive 계정에서 데이터를 스캔할 경우 이러한 클라우드 위치 중 아무 곳에서나 커넥터를 사용할 수 있습니다.


따라서 여러 위치에 데이터가 있는 경우 를 사용해야 할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["다중 커넥터"].



=== 내 호스트에 커넥터를 배포할 수 있습니까?

예. 가능합니다 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html["Connector를 온-프레미스에 배포합니다"^] 네트워크 또는 클라우드의 Linux 호스트 온-프레미스에 데이터 센스를 배포하려는 경우 Connector를 온-프레미스에도 설치할 수 있지만 필요하지 않습니다.



=== 인터넷에 연결되지 않은 보안 사이트는 어떻게 됩니까?

예, 지원합니다. 가능합니다 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["인터넷에 액세스할 수 없는 온프레미스 Linux 호스트에 커넥터를 배포합니다"]. 그런 다음 사내 ONTAP 클러스터와 기타 로컬 데이터 소스를 검색하고 데이터 센스를 사용하여 데이터를 검색할 수 있습니다.



== 데이터 감지 구축

다음 질문은 별도의 데이터 감지 인스턴스와 관련이 있습니다.



=== 클라우드 데이터 센스에 필요한 인스턴스 또는 VM 유형은 무엇입니까?

시기 link:task-deploy-cloud-compliance.html["클라우드에 구축"]:

* AWS에서 Cloud Data Sense는 500GB GP2 디스크가 있는 m5.4x대용량 인스턴스에서 실행됩니다.
* Azure에서 클라우드 데이터 센스(Cloud Data Sense)는 512GB 디스크가 있는 Standard_D16s_v3 VM에서 실행됩니다.
* GCP에서 Cloud Data Sense는 512GB의 표준 영구 디스크가 있는 n2-standard-16 VM에서 실행됩니다.


CPU가 적고 RAM이 적은 시스템에 데이터 센스를 배포할 수 있지만 이러한 시스템을 사용할 때는 한계가 있습니다. 을 참조하십시오 link:concept-cloud-compliance.html#using-a-smaller-instance-type["더 작은 인스턴스 유형 사용"] 를 참조하십시오.

link:concept-cloud-compliance.html["클라우드 데이터 센스의 작동 방식에 대해 자세히 알아보십시오"^].



=== 자체 호스트에 데이터 센스를 구축할 수 있습니까?

예. 네트워크 또는 클라우드에서 인터넷에 액세스할 수 있는 Linux 호스트에 Data Sense 소프트웨어를 설치할 수 있습니다. 모든 기능이 동일하게 작동하며 Cloud Manager를 통해 스캔 구성과 결과를 지속적으로 관리할 수 있습니다. 을 참조하십시오 link:task-deploy-compliance-onprem.html["온프레미스에서 클라우드 데이터 센스를 구축하는 중입니다"] 시스템 요구 사항 및 설치 세부 정보를 확인하십시오.



=== 인터넷에 연결되지 않은 보안 사이트는 어떻게 됩니까?

예, 지원합니다. 가능합니다 link:task-deploy-compliance-dark-site.html["인터넷에 액세스할 수 없는 온프레미스 사이트에 데이터 센스를 구현합니다"] 완전히 안전한 사이트를 위한 것입니다.
