---
sidebar: sidebar 
permalink: reference-private-data-categories.html 
keywords: personal files, personal data, sensitive personal files, sensitive personal data, categories, health data, ethnic origin, political opinions, gdpr, email address, credit card, ip address, iban, national ID, identifier, sex, criminal, compliance, privacy, 
summary: Cloud Data Sense는 볼륨, Amazon S3 버킷, 데이터베이스, OneDrive 폴더 및 SharePoint 계정에서 여러 유형의 프라이빗 데이터를 식별할 수 있습니다. 아래 범주를 참조하십시오. 
---
= 개인 데이터의 범주입니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Data Sense는 볼륨, Amazon S3 버킷, 데이터베이스, OneDrive 폴더 및 SharePoint 계정에서 여러 유형의 프라이빗 데이터를 식별할 수 있습니다. 아래 범주를 참조하십시오.


TIP: Cloud Data Sense를 사용하여 추가 국가 ID 번호 또는 의료 식별자 등과 같은 다른 프라이빗 데이터 유형을 식별하려면 ng-contact-data-sense@netapp.com 으로 이메일을 보내 요청하십시오.



== 개인 데이터의 유형입니다

파일에서 발견된 개인 데이터는 일반 개인 데이터 또는 국가 식별자일 수 있습니다. 세 번째 열에는 Cloud Data Sense가 사용되는지 여부를 확인할 수 있습니다 link:task-controlling-private-data.html#viewing-files-that-contain-personal-data["근접 확인"^] 식별자에 대한 결과를 검증합니다.

이 범주의 항목은 모든 언어로 인식할 수 있습니다.

데이터베이스 서버를 검색하는 경우 파일에 있는 개인 데이터 목록에 추가할 수 있습니다. Data Fusion_Feature를 사용하면 데이터베이스 테이블에서 열을 선택하여 클라우드 데이터 센스가 '스캔'에서 찾을 추가 식별자를 선택할 수 있습니다. 을 참조하십시오 link:task-managing-data-fusion.html["Data Fusion를 사용하여 개인 데이터 식별자를 추가합니다"^] 를 참조하십시오.

[cols="20,50,18"]
|===
| 유형 | ID입니다 | 근접성 검증? 


.5+| 일반 | 이메일 주소입니다 | 아니요 


| 신용 카드 번호입니다 | 아니요 


| IBAN 번호(국제 은행 계좌 번호) | 아니요 


| IP 주소입니다 | 아니요 


| 암호 | 예 


.42+| 국가 식별자 | 오스트레일리아 TFN(세금 파일 번호) | 예 


| 오스트레일리아 운전면허증 번호 | 예 


| 오스트레일리아 의료 보험 번호 | 예 


| 호주 여권 번호 | 예 


| 오스트리아 주민등록번호 | 예 


| 벨기에 iD(Numero National) | 예 


| 브라질 ID(CPF) | 예 


| 영국 여권 | 예 


| 불가리아어 ID(UCN) | 예 


| 캘리포니아 운전면허증 | 예 


| 크로아티아어 ID(OIB) | 예 


| 키프로스 세금 식별 번호(TIC) | 예 


| 체코어/슬로바키아어 ID | 예 


| 덴마크어 ID(CPR) | 예 


| 네덜란드어 ID(BSN) | 예 


| 에스토니아어 ID | 예 


| 핀란드 iD(HETU) | 예 


| 프랑스어 드라이버 라이센스 | 예 


| 프랑스어 ID | 예 


| 프랑스 인세어 | 예 


| 프랑스어 주민 등록 번호 | 예 


| 프랑스어 세금 식별 번호(SPI) | 예 


| 독일 세금 식별 번호(슈테루리체 식별 번호) | 예 


| 그리스어 ID | 예 


| 헝가리 세금 식별 번호 | 예 


| 아일랜드 ID(PPS) | 예 


| 이스라엘 iD | 예 


| 이탈리아 세금 식별 번호 | 예 


| 라트비아어 ID | 예 


| 리투아니아어 ID | 예 


| 룩셈부르크 ID입니다 | 예 


| 몰타 ID | 예 


| NHS(National Health Service) 번호 | 예 


| 폴란드어 ID(PESEL) | 예 


| 포르투갈어 세금 식별 번호(NIF) | 예 


| 루마니아어 ID(CNP) | 예 


| 슬로베니아어 ID(EMSO) | 예 


| 남아프리카 ID | 예 


| 스페인어 세금 식별 번호 | 예 


| 스웨덴 iD | 예 


| 영국 ID(Nino) | 예 


| 미국 주민등록번호 | 예 
|===


== 중요한 개인 데이터의 유형

Cloud Data Sense가 파일에서 찾을 수 있는 중요한 개인 데이터에는 다음 목록이 포함됩니다. 이 범주의 항목은 현재 영어로만 인식할 수 있습니다.

형사 절차 참조:: 자연인의 범죄 소신 및 범죄에 관한 데이터.
인종 참조:: 자연인의 인종 또는 민족에 관한 데이터.
상태 참조:: 자연인의 건강에 관한 데이터.
ICD-9-cm 의료 코드:: 의료 및 의료 산업에서 사용되는 코드.
ICD-10-CM 의료 코드:: 의료 및 의료 산업에서 사용되는 코드.
철학적 신념 기준:: 자연인의 철학적 신념에 관한 데이터.
정치적 견해 참조:: 자연인의 정치적 의견에 관한 자료.
종교적 신념 참조:: 자연인의 종교적 신념에 관한 데이터.
성생활 또는 오리엔테이션 참조:: 자연인의 성생활 또는 성적 취향과 관련된 데이터.




== 범주 유형

Cloud Data Sense는 다음과 같이 데이터를 분류합니다. 이러한 범주의 대부분은 영어, 독일어 및 스페인어로 인정될 수 있습니다.

[cols="25,25,15,15,15"]
|===
| 범주 | 유형 | 영어 | 독일어 | 스페인어 


.4+| 재무 | 밸런스 시트 | ✓ | ✓ | ✓ 


| 구매 주문 | ✓ | ✓ | ✓ 


| 인보이스 | ✓ | ✓ | ✓ 


| 분기별 보고서 | ✓ | ✓ | ✓ 


.6+| 시간 | 배경 확인 | ✓ |  | ✓ 


| 보상 계획 | ✓ | ✓ | ✓ 


| 직원 계약 | ✓ |  | ✓ 


| 직원 검토 | ✓ |  | ✓ 


| 상태 | ✓ |  | ✓ 


| 다시 시작합니다 | ✓ | ✓ | ✓ 


.2+| 법적 고지 | NDAS | ✓ | ✓ | ✓ 


| 공급업체 - 고객 계약 | ✓ | ✓ | ✓ 


.2+| 마케팅 | 캠페인 | ✓ | ✓ | ✓ 


| 회의 | ✓ | ✓ | ✓ 


| 운영 | 감사 보고서 | ✓ | ✓ | ✓ 


| 판매 | 판매 주문 | ✓ | ✓ |  


.4+| 서비스 | RFI | ✓ |  | ✓ 


| RFP | ✓ |  | ✓ 


| SOW | ✓ | ✓ | ✓ 


| 교육 | ✓ | ✓ | ✓ 


| 지원 | 불만 및 티켓 | ✓ | ✓ | ✓ 
|===
다음 메타데이터도 분류되어 동일한 지원 언어로 식별됩니다.

* 애플리케이션 데이터
* 파일 보관
* 오디오
* 비즈니스 애플리케이션 데이터
* CAD 파일
* 코드
* 손상되었습니다
* 데이터베이스 및 인덱스 파일
* 설계 파일
* 이메일 애플리케이션 데이터
* 암호화
* 실행 파일
* 재무 애플리케이션 데이터
* 상태 응용 프로그램 데이터
* 이미지
* 로그
* 기타 문서
* 기타 프레젠테이션
* 기타 스프레드시트
* 기타 "알 수 없음"
* 정형 데이터
* 비디오
* 0바이트 파일




== 파일 유형

Cloud Data Sense는 모든 파일에서 범주 및 메타데이터 정보를 검색하고 대시보드의 파일 형식 섹션에 모든 파일 형식을 표시합니다.

그러나 데이터 센스에서 PII(개인 식별 정보)를 감지하거나 DSAR 검색을 수행할 경우 다음 파일 형식만 지원됩니다.

'+.csv, .dcm, .dicom, .DOC, .DOCX, .JSON, .pdf, .PPTX, .rtf, .TXT, XLS 및 .XLSX.+'



== 정보가 정확합니다

NetApp은 Cloud Data Sense에서 식별할 수 있는 개인 데이터와 민감한 개인 데이터의 100% 정확성을 보장할 수 없습니다. 항상 데이터를 검토하여 정보의 유효성을 확인해야 합니다.

테스트를 기준으로 아래 표는 Data Sense에서 찾은 정보의 정확성을 보여줍니다. 정밀 _ 및 _ 리콜 _ 을(를) 통해 분해합니다.

정밀도:: 데이터 센스에서 발견한 것이 정확하게 식별되었을 확률입니다. 예를 들어, 개인 데이터의 정밀도가 90%이면 개인 정보가 포함된 것으로 확인된 10개 파일 중 9개가 개인 정보를 포함하고 있음을 의미합니다. 10개 파일 중 1개는 위양성입니다.
리콜:: 데이터 센스에서 필요한 것을 찾을 수 있는 확률입니다. 예를 들어 개인 데이터의 리콜 비율이 70%이면 데이터 센스에서 조직에 개인 정보가 실제로 포함된 10개 파일 중 7개를 식별할 수 있습니다. 데이터 센스에서 데이터의 30%를 누락하면 대시보드에 표시되지 않습니다.


우리는 결과의 정확성을 지속적으로 개선하고 있습니다. 이러한 향상된 기능은 향후 Data Sense 릴리즈에서 자동으로 제공될 예정입니다.

[cols="25,20,20"]
|===
| 유형 | 정밀도 | 리콜 


| 개인 데이터 - 일반 | 90% - 95% | 60%~80% 


| 개인 데이터 - 국가 식별자 | 30% ~ 60% | 40% ~ 60% 


| 민감한 개인 데이터 | 80% - 95% | 20% - 30% 


| 범주 | 90% - 97% | 60%~80% 
|===