---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: 클라우드 데이터 센스의 새로운 기능에 대해 알아보십시오. 
---
= 클라우드 데이터 센스의 새로운 기능
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
클라우드 데이터 센스의 새로운 기능에 대해 알아보십시오.



== 2022년 4월 5일



=== 네 가지 새로운 유형의 호주 개인 데이터는 데이터 센스로 식별할 수 있습니다

데이터 센스를 사용하면 오스트레일리아 TFN(세금 파일 번호), 오스트레일리아 운전면허증 번호, 오스트레일리아 의료보험 번호 및 호주 여권 번호가 포함된 파일을 식별하고 분류할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["데이터 센스에서 식별할 수 있는 모든 유형의 개인 데이터를 확인하십시오"].



=== 이제 글로벌 Active Directory 서버가 LDAP 서버가 될 수 있습니다

Data Sense와 통합하는 글로벌 Active Directory 서버는 이제 이전에 지원되는 DNS 서버 외에도 LDAP 서버가 될 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-add-active-directory-datasense.html["자세한 내용을 보려면 여기를 클릭하십시오"].



== 2022년 3월 15일



=== 새 필터 - 특정 사용자 또는 그룹에 읽기 또는 쓰기 권한이 있는 파일을 표시합니다

"사용자/그룹 권한"이라는 새 필터가 추가되어 특정 사용자 또는 그룹에 읽기 및/또는 쓰기 권한이 있는 파일을 나열할 수 있습니다. 사용자 이름 또는 그룹 이름 또는 부분 이름을 지정할 수 있습니다. 이 기능은 Cloud Volumes ONTAP, 온프레미스 ONTAP, Azure NetApp Files, ONTAP용 Amazon FSx 및 파일 공유의 볼륨에 사용할 수 있습니다.



=== Data Sense는 SharePoint 및 OneDrive 계정의 파일에 대한 사용 권한을 결정할 수 있습니다

Data Sense는 지금 OneDrive 계정 및 SharePoint 계정에서 스캔되는 파일에 대한 사용 권한을 읽을 수 있습니다. 이 정보는 파일에 대한 조사 창 세부 정보와 거버넌스 대시보드의 열기 권한 영역에 표시됩니다.



=== 데이터 센스로 두 가지 유형의 개인 데이터를 추가로 식별할 수 있습니다

* 프랑스어 INSEE - INSEE 코드는 프랑스 통계 및 경제 연구(INSEE)에서 다양한 엔터티를 식별하기 위해 사용하는 숫자 코드입니다.
* 암호 - 이 정보는 영숫자 문자열 옆에 있는 "password"라는 단어의 변이를 찾아 근접 유효성 검사를 통해 식별됩니다. 찾은 항목 수는 규정 준수 대시보드의 "개인 결과" 아래에 나열됩니다. 검색 창에서 Filter * Personal Data > Password * 를 사용하여 암호가 포함된 파일을 검색할 수 있습니다.




=== 어두운 사이트에 배포할 때 OneDrive 및 SharePoint 데이터 스캔 지원

인터넷에 액세스할 수 없는 온프레미스 사이트의 호스트에 Cloud Data Sense를 배포했다면 이제 OneDrive 계정 또는 SharePoint 계정에서 로컬 데이터를 검색할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-dark-site.html#sharepoint_and_onedrive_special_requirements["다음 끝점에 대한 액세스를 허용해야 합니다."]



=== Cloud Data Sense를 사용하여 Cloud Backup 파일을 검사하는 베타 기능은 이 릴리즈에서 더 이상 제공되지 않습니다



== 2022년 2월 9일



=== Microsoft SharePoint 온라인 계정 검색에 대한 지원이 추가되었습니다

이제 SharePoint 사이트의 문서 및 파일을 스캔하기 위해 SharePoint 온라인 계정을 데이터 센스에 추가할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html["SharePoint 계정을 검색하는 방법을 알아봅니다"].



=== Data Sense는 데이터 소스에서 타겟 위치로 파일을 복사하고 이러한 파일을 동기화할 수 있습니다

이 기능은 데이터를 마이그레이션할 때 파일의 마지막 변경 내용을 확인하고자 하는 경우에 유용합니다. 이 작업은 를 사용합니다 https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["NetApp Cloud Sync를 참조하십시오"^] 소스에서 타겟으로 데이터를 복제 및 동기화하는 기능

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system["파일 복사 및 동기화 방법을 참조하십시오"].



=== SAR 보고서에 대한 새로운 언어 지원

DSAR(Data Subject Access Request) 보고서를 생성하기 위해 데이터 주체 이름을 검색할 때 독일어 및 스페인어가 지원됩니다. 이 보고서는 GDPR 또는 이와 유사한 데이터 개인 정보 보호 법률을 준수하기 위한 조직의 요구 사항을 돕기 위해 작성되었습니다.



=== 데이터 센스를 통해 세 가지 유형의 개인 데이터를 추가로 식별할 수 있습니다

이제 Data Sense는 파일에서 프랑스어 주민등록번호, 프랑스어 ID 및 프랑스어 드라이버 라이센스 번호를 찾을 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["스캔 시 데이터 센스에서 식별하는 모든 개인 데이터 유형 목록을 참조하십시오"].



=== 커넥터에 대한 데이터 감지 통신을 위해 보안 그룹 포트가 변경되었습니다

Cloud Manager Connector의 보안 그룹은 보안을 강화하기 위해 Data Sense 인스턴스에 대한 인바운드 및 아웃바운드 트래픽에 포트 80 대신 포트 443을 사용합니다. 두 포트 모두 현재 열려 있으므로 문제가 발생하지 않도록 해야 합니다. 하지만 포트 80은 향후 릴리스에서 더 이상 사용되지 않으므로 이전 버전의 Connector 배포에서 보안 그룹을 업데이트해야 합니다.



== 2022년 1월 2일



=== 글로벌 Active Directory를 통합하여 파일 소유자 및 권한을 식별하는 기능입니다

이제 글로벌 Active Directory를 클라우드 데이터 센스와 통합하여 파일 소유자에 대한 데이터 센스 보고서와 파일에 액세스할 수 있는 사용자 및 그룹에 대한 결과를 개선할 수 있습니다.

Data Sense가 특정 데이터 소스에서 CIFS 볼륨을 스캔할 수 있도록 입력하는 Active Directory 자격 증명 외에도 이 새로운 통합은 다른 사용자 및 시스템을 위한 추가 통합 기능을 제공합니다. 데이터 센스(Data Sense)는 모든 통합 Active Directory에서 사용자 및 권한 세부 정보를 찾습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-add-active-directory-datasense.html["글로벌 Active Directory를 설정하는 방법을 확인하십시오"].



=== 이제 데이터 감지 "정책"을 사용하여 파일을 삭제할 수 있습니다

Data Sense는 정책에 정의한 쿼리와 일치하는 파일을 자동으로 삭제할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#deleting-source-files-automatically-using-policies["사용자 지정 정책을 만드는 방법을 알아봅니다"].



== 2021년 12월 16일



=== 데이터 감지 기능으로 어두운 사이트에서 데이터를 스캔할 수 있습니다

Cloud Manager(커넥터)와 Cloud Data Sense는 모두 인터넷에 액세스할 수 없는 사내 사이트에 배포할 수 있습니다. 이제 클라우드 관리자를 사용하여 온프레미스 ONTAP 클러스터를 관리하고, 클러스터 간에 데이터를 복제하며, 클라우드 데이터 센스를 사용하여 클러스터에서 데이터를 검색할 수 있습니다.

link:task-deploy-compliance-dark-site.html["인터넷에 연결되지 않은 사이트에 클라우드 데이터 센스를 구축하는 방법을 알아보십시오"^].



== 2021년 11월 28일



=== Data Sense는 ONTAP 시스템에서 볼륨을 복제하는 데 사용할 수 있습니다

데이터 센스를 사용하여 ONTAP 볼륨을 복제할 수 있지만 소스 볼륨에서 선택한 파일만 새 클론 복제된 볼륨에 포함할 수 있습니다. 이 기능은 데이터를 마이그레이션하는 동안 특정 파일을 제외하려는 경우 또는 테스트할 볼륨의 복사본을 만들려는 경우에 유용합니다.

link:task-managing-highlights.html#cloning-volume-data-to-a-new-volume["볼륨을 복제하는 방법을 확인하십시오"].



=== Cloud Manager의 GCP Marketplace 구독에 이제 Cloud Data Sense에 대한 지원이 포함됩니다

를 클릭합니다 https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project&rif_reserved["Cloud Manager용 GCP Marketplace 구독"^] 이제 클라우드 데이터 센스에 대한 지원이 포함됩니다. 이제 이 PAYGO(Pay-as-you-Go) 구독을 사용하여 Google Cloud 스토리지에 구축된 Cloud Volumes ONTAP 시스템에서 BYOL 라이센스를 사용할 뿐만 아니라 데이터를 스캔할 수 있습니다.



=== 장기 실행 준수 작업의 상태를 볼 수 있는 기능

50개의 파일을 삭제하는 등 여러 파일에 대해 조사 결과 창에서 작업을 실행할 경우 프로세스에 약간의 시간이 걸릴 수 있습니다. 이제 이러한 비동기 작업의 상태를 모니터링하여 모든 파일에 언제 적용되었는지 알 수 있습니다.

link:task-managing-highlights.html#viewing-the-status-of-your-compliance-actions["진행 중인 규정 준수 작업의 상태를 확인하는 방법을 알아봅니다"].



=== 데이터 센스로 두 가지 유형의 개인 데이터를 추가로 식별할 수 있습니다

이제 데이터 센스에서 파일의 개인 데이터 유형인 "영국 여권" 및 "국립보건원(NHS) 번호"를 찾을 수 있습니다. link:reference-private-data-categories.html#types-of-personal-data["스캔 시 데이터 센스에서 찾는 모든 개인 데이터 유형 목록을 참조하십시오"].



=== 새 필터 - 특정 작업 환경 유형에 속하는 파일을 표시합니다

데이터 조사 페이지에서 데이터를 필터링할 때 "작업 환경 유형"에 대한 새 필터가 추가되었습니다. 이를 통해 Cloud Volumes ONTAP 시스템, ONTAP 시스템용 FSx, 온프레미스 ONTAP 시스템 등에 대한 결과를 필터링할 수 있습니다.



== 2021년 11월 7일



=== 이제 작업 환경에서 개별 볼륨을 매핑하거나 분류할 수 있습니다

과거에는 모든 볼륨을 매핑하거나 각 작업 환경의 모든 볼륨을 매핑 및 분류할 수 있었습니다. 이제 개별 볼륨을 매핑_또는_매핑 및 분류할 수 있습니다. 이 옵션은 Cloud Volumes ONTAP 볼륨, ANF 볼륨, 온프레미스 ONTAP 볼륨 및 ONTAP 볼륨용 FSx에 사용할 수 있습니다.



=== Data Sense는 데이터 소스에서 대상 NFS 공유로 파일을 복사할 수 있습니다

Data Sense에서 검색 중인 소스 파일을 대상 NFS 공유에 복사할 수 있습니다. 이 기능은 특정 데이터의 복제본을 만들어 다른 NFS 위치로 이동하려는 경우 유용합니다. link:task-managing-highlights.html#copying-source-files-to-an-nfs-share["자세한 정보"].



=== FSx에서 ONTAP 파일 시스템용 데이터 보호 볼륨을 스캔할 수 있습니다

이제 FSx에서 ONTAP 파일 시스템용 데이터 보호 볼륨을 스캔할 수 있습니다. link:task-scanning-fsx.html#scanning-data-protection-volumes["자세한 정보"].



=== 데이터 센스를 처음 검색한 날짜 범위별로 파일을 표시하는 새 필터

"검색된 시간"이라는 조사 페이지의 새 필터를 사용하면 데이터 센스에서 파일을 처음 검색한 날짜 범위별로 파일을 볼 수 있습니다. 검색 시간도 파일 세부 정보 페이지 및 파일에 대해 CSV 형식으로 출력한 보고서에 추가되었습니다.



=== SOC 2 Type 2 인증

독립 공인 회계사 및 서비스 감사원이 Cloud Data Sense를 조사하여 해당 신뢰 서비스 기준에 따라 SOC 2 Type 2 보고서를 획득하였다는 것을 확인했습니다.

https://www.netapp.com/company/trust-center/compliance/soc-2/["NetApp의 SOC 2 보고서 보기"^].



== 2021년 10월 4일



=== NetApp의 BYOL 라이센싱 지원

클라우드 공급자 마켓플레이스를 통해 데이터 센스를 라이센스하는 것 외에도, 이제 NetApp에서 BYOL(Bring-Your-Own-License)을 구매하여 Cloud Manager 계정의 모든 작업 환경 및 데이터 소스에서 사용할 수 있습니다.

link:task-licensing-datasense.html#use-a-cloud-data-sense-byol-license["새로운 Cloud Data Sense BYOL 라이센스에 대해 자세히 알아보십시오"].



=== Google Cloud Platform 지원

이제 클라우드 데이터 센스를 통해 GCP에 구축된 Cloud Volumes ONTAP 시스템에서 데이터를 검색할 수 있습니다. 데이터 센스를 GCP에 구축해야 하며 커넥터는 GCP 또는 온프레미스에 구축해야 합니다. Connector와 연결된 GCP 서비스 계정은 Cloud Data Sense to GCP를 배포하기 위한 최신 권한이 필요합니다.



=== FSx에서 ONTAP 파일 시스템용 CIFS 볼륨을 스캔할 수 있습니다

이제 Data Sense는 ONTAP 시스템용 FSx에서 CIFS 볼륨을 스캔할 수 있습니다. link:task-scanning-fsx.html["ONTAP 볼륨에 대해 Amazon FSx를 스캔하는 방법을 확인하십시오"].



== 2021년 9월 2일



=== FSx에서 ONTAP 파일 시스템용 NFS 볼륨을 스캔할 수 있습니다

ONTAP 시스템용 Amazon FSx의 NFS 볼륨에서 데이터를 스캔하는 기능이 추가되었습니다. link:task-scanning-fsx.html["ONTAP 시스템에 대한 FSx 검사를 구성하는 방법을 참조하십시오"].



=== 데이터 감지 "상태" 항목이 "태그" 항목으로 변경되었습니다

Data Sense를 사용하여 파일에 "상태" 정보를 추가하는 기능이 용어를 "태그"로 변경했습니다. 이러한 태그는 파일 레벨 태그이며 볼륨, EC2 인스턴스, 가상 머신 등에 적용할 수 있는 리소스 레벨 태깅과 혼동하지 않습니다 link:task-org-private-data.html#applying-tags-to-manage-your-scanned-files["파일 레벨 태그에 대해 자세히 알아보십시오"].



== 2021년 8월 1일



=== 한 번에 여러 파일의 파일 설정을 관리할 수 있습니다

이전 버전의 Cloud Data Sense에서는 상태 태그 추가, 사용자 할당 및 AIP 레이블 추가와 같은 작업을 한 번에 한 파일에 수행할 수 있습니다. 이제 데이터 조사 페이지에서 여러 파일을 선택하고 여러 파일에 대해 각 작업을 수행할 수 있습니다.



=== 거버넌스 대시보드에는 데이터가 생성된 시점 또는 마지막으로 액세스한 시별 데이터가 표시됩니다

마지막으로 수정한 시간을 기준으로 데이터를 볼 수 있을 뿐 아니라 Governance 대시보드에서 데이터 사용 기간 그래프를 볼 때는 데이터가 생성된 시점 또는 마지막으로 액세스한 시점(읽었을 때)을 기준으로 데이터를 볼 수 있습니다. 이 정보는 데이터 매핑 보고서에도 제공됩니다.



=== 대규모 구성을 스캔할 때 추가 처리 성능을 위해 여러 호스트를 사용할 수 있습니다

이제 온프레미스에 Data Sense를 구축할 때 페타바이트 데이터를 포함하는 구성을 스캔하려는 경우 추가 온프레미스 호스트에 스캐닝 소프트웨어를 설치할 수 있습니다. 이러한 추가 _scanner 노드는 매우 큰 구성을 스캔할 때 처리 능력을 높여 줍니다.

자세한 내용은 를 참조하십시오 link:task-deploy-compliance-onprem.html#multi-host-installation-for-large-configurations["여러 호스트에 데이터 감지 소프트웨어를 배포합니다"].



== 2021년 7월 7일



=== 데이터 센스를 사용하면 데이터 소스에서 대상 NFS 공유로 파일을 이동할 수 있습니다

새로운 기능을 통해 를 수행할 수 있습니다 link:task-managing-highlights.html#moving-source-files-to-an-nfs-share["데이터 센스에서 스캔 중인 소스 파일을 모든 NFS 공유로 이동합니다"]. 따라서 중요한 파일이나 보안 관련 파일을 특수 영역으로 이동하여 더 많은 분석을 수행할 수 있습니다.



=== 전체 분류 스캔을 수행하는 대신 데이터를 신속하게 범주화할 수 있습니다

이제 전체 분류 스캔을 수행하는 대신 데이터를 범주로 빠르게 매핑할 수 있습니다. 이를 통해 를 수행할 수 있습니다 link:task-generating-compliance-reports.html#data-mapping-report["데이터 매핑 보고서를 봅니다"] 거버넌스 대시보드에서 전체 스캔을 실행할 필요가 없는 특정 데이터 소스가 있을 때 데이터에 대한 개요를 확인할 수 있습니다.



=== Cloud Manager 사용자에게 파일을 할당할 수 있습니다

이제 가능합니다 link:task-org-private-data.html#assigning-users-to-manage-certain-files["특정 Cloud Manager 사용자에게 파일을 할당합니다"] 따라서 해당 파일에 대해 수행해야 하는 모든 후속 조치에 대해 책임을 질 수 있습니다. 이 기능을 기존 기능과 함께 사용하여 파일에 사용자 지정 태그를 추가할 수 있습니다.

또한 조사 페이지의 새 필터를 사용하면 "담당자" 필드에 동일한 사람이 있는 모든 파일을 쉽게 볼 수 있습니다.



=== 더 작은 Cloud Data Sense 인스턴스를 사용할 수 있습니다

스캔 요구 사항이 적은 일부 사용자는 더 작은 Cloud Data Sense 인스턴스를 사용할 수 있어야 했습니다. 이제 가능합니다. 이러한 작은 인스턴스를 사용할 때는 몇 가지 제한 사항이 있습니다 link:concept-cloud-compliance.html#using-a-smaller-instance-type["이러한 제한 사항이 무엇인지 먼저 확인하십시오"].



=== 저속 스캔 수행 기능

데이터 스캔은 스토리지 시스템과 데이터에 경미한 영향을 줍니다. 하지만 아주 작은 충격에도 신경 쓰면 데이터 센스를 구성하여 "느린" 스캔을 수행할 수 있습니다. link:task-managing-compliance.html#reducing-the-data-sense-scan-speed["방법을 확인하십시오"].



=== Data Sense는 파일에 마지막으로 액세스한 시간을 추적합니다

마지막으로 액세스한 시간 값이 파일 세부 정보 페이지 및 CSV 형식으로 출력되는 보고서에 추가되어 사용자가 마지막으로 파일에 액세스한 시간을 확인할 수 있습니다.



== 2021년 6월 7일



=== Cloud Compliance는 Cloud Data Sense로 이름이 바뀌었습니다.

이번 릴리즈로 Cloud Compliance의 이름이 * Cloud Data Sense * 로 변경되었습니다. 제품에 포함된 모든 새로운 거버넌스 및 기타 기능을 통해 규정 준수 이름은 전체 기능 세트를 홍보하지 않았습니다.



=== 거버넌스 대시보드에서 새로운 "전체 데이터 매핑" 보고서를 사용할 수 있습니다

Governance Dashboard에서 새로운 _Full Data Mapping_Report를 사용하여 마이그레이션, 백업, 보안 및 규정 준수 프로세스 결정에 도움이 되도록 기업 데이터 소스에 저장되는 데이터에 대한 개요를 제공할 수 있습니다.

이 보고서는 모든 작업 환경 및 데이터 소스를 요약하고 각 작업 환경에 대한 분석을 제공하는 개요 페이지를 제공합니다. link:task-generating-compliance-reports.html#generating-the-data-mapping-report["여기로 이동"] 를 참조하십시오.



=== 조사 페이지의 새 필터를 사용하여 모든 중복 파일을 봅니다

데이터 조사 페이지의 새 필터를 사용하면 스토리지 시스템 전체에서 복제된 모든 파일의 목록을 볼 수 있습니다. 이 기능은 저장소 공간을 절약할 수 있는 영역을 식별하거나, 저장소 전체에서 복제하지 않으려는 특정 사용 권한이나 중요한 정보가 있는 파일을 식별하는 데 유용합니다. link:task-controlling-private-data.html#viewing-all-duplicated-files["모든 중복 파일을 보는 방법을 확인하십시오"].



=== Data Sense는 사용자 지정 태그를 조직용 파일에 추가할 수 있습니다

데이터 센스에서 스캔 중 파일에 사용자 정의 태그를 추가할 수 있습니다. 태그가 AIP 라벨과 같은 방식으로 파일에 추가되지 않습니다. 이 태그는 Cloud Manager 사용자가 볼 수 있으므로 어떤 이유로 파일을 삭제하거나 확인해야 하는지 여부를 나타낼 수 있습니다. link:task-org-private-data.html#applying-tags-to-manage-your-scanned-files["파일에서 태그를 적용하고 보는 방법을 알아봅니다"].

조사 페이지의 새 필터를 사용하면 태그가 지정된 모든 파일을 쉽게 볼 수 있습니다.



=== DCM 및 .DICOM 파일 스캔 기능

Cloud Data Sense는 .dcm 및 .dicom의 두 가지 추가 파일 유형에서 개인 식별 정보(PII)를 검색할 수 있습니다.



=== 이제 데이터 센스에서 파일의 추가 속성을 추적합니다

CSV 형식으로 출력하는 보고서에 파일 크기, 만든 날짜 및 마지막으로 수정한 날짜 값이 추가되었습니다. 만든 날짜 는 조사 페이지 검색 결과의 범위를 좁히는 데 사용할 수 있는 새 필터이기도 합니다.



== 2021년 5월 5일



=== Azure Blob에 저장된 데이터를 스캔할 수 있습니다

이제 를 사용할 때 Azure Blob에 저장된 데이터 스캔이 지원됩니다 https://min.io/["MinIO 서비스"^]. 을 참조하십시오 link:task-scanning-object-storage.html["S3 프로토콜을 사용하는 오브젝트 스토리지 스캔"] 를 참조하십시오.



=== 추가적인 개인 데이터 유형은 데이터 센스로 식별할 수 있습니다

Cloud Data Sense는 이제 파일에서 오스트리아 SSN을 찾을 수 있습니다.
